### ISSUE TITLE
希望可以做一个帮助页面

### ISSUE THREAD

**Issue by SaltyFishAB** [XasYer/steam-plugin#23]
功能太多了不一定记得住喵

**Comment by XasYer** [comment]
???不是有吗 `steam帮助`

**Comment by SaltyFishAB** [comment]
最开始使用指令的时候直接变成搜索了
![c3091eb3-5489-4bd1-995a-f647956a4f90](https://github.com/user-attachments/assets/d2862296-4658-4c55-9e17-737b44eec1cc)

**Comment by XasYer** [comment]
被其他插件抢指令了

**Comment by XasYer** [comment]
发送`#更新steam-plugin` 更新到最新, 可以设置插件优先级`#steam设置优先级1` ,数值越小优先级越高, 重启后生效
