### ISSUE TITLE
steam与绑定的bot强关联

### ISSUE THREAD

**Issue by chz091** [XasYer/steam-plugin#32]
大佬，目前发现一个问题，如果是在1号QQ绑定的steam，因为某些不可抗性的原因1号QQ封号了，yunzai更改另外一个QQ登录的时候，steam不会再进行播报，查了一下插件下的data目录里的db文件，发现绑定信息似乎和BOT的qq号绑定，从而导致新的QQ没办法推送状态

**Comment by XasYer** [comment]
如果是TRSS, 更新后发`#steam设置随机Bot开启`, 如果新Bot和旧Bot在同一个群则会继续推送, 如果是Miao自行解决

**Comment by chz091** [comment]
> 如果是TRSS, 更新后发`#steam设置随机Bot开启`, 如果新Bot和旧Bot在同一个群则会继续推送, 如果是Miao自行解决

感谢佬
